export const MOSTRAR_MASCOTAS = "MOSTRAR_MASCOTAS";
export const MOSTRAR_MASCOTA = "MOSTRAR_MASCOTA";
export const EDITAR_MASCOTA = "EDITAR_MASCOTA";
export const ELIMINAR_MASCOTA = "ELIMINAR_MASCOTA";
export const AGREGAR_MASCOTA = "AGREGAR_MASCOTA";

export const MOSTRAR_CITAS = "MOSTRAR_CITAS";
export const ELIMINAR_CITA = "ELIMINAR_CITA";
export const AGREGAR_CITA = "AGREGAR_CITA";


export const MOSTRAR_VACUNA = "MOSTRAR_VACUNA";
export const EDITAR_VACUNA = "EDITAR_VACUNA";
export const ELIMINAR_VACUNA = "ELIMINAR_VACUNA";
export const AGREGAR_VACUNA = "AGREGAR_VACUNA";

